on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee 💕
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACTION_DEPLOY_KEY_BLOG_PRI }}
        with:
          source-repo: 'git@github.com:bujidao/awesome-bookmarks.git'
          destination-repo: 'git@github.com:bujidao/awesome-bookmarks.git'
